#ifndef PAGETESALLIANCE_GLOBAL_H
#define PAGETESALLIANCE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PAGETESALLIANCE_LIBRARY)
#  define PAGETESALLIANCESHARED_EXPORT Q_DECL_EXPORT
#else
#  define PAGETESALLIANCESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PAGETESALLIANCE_GLOBAL_H
